spring.application.name=backend
spring.config.import=optional:classpath:adzuna.properties,optional:classpath:.env[.properties]
spring.datasource.url=jdbc:postgresql://localhost:5432/realmcheck?options=-c%20timezone=UTC
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Spring SQL Initialization
spring.sql.init.mode=never
spring.sql.init.platform=postgres

# Adzuna API (Phase 2)
adzuna.app.id=${ADZUNA_APP_ID}
adzuna.app.key=${ADZUNA_APP_KEY}

apify.api.token=${APIFI_API_TOKEN}
bodhdisha.api.key=${BODHDISHA_API_KEY}
